services:
  - type: web
    name: duwaz-backend
    runtime: java
    rootDir: Backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/DUWAZ-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: "21"
